#!/bin/sh

# aur a simple aur manager

CACHE_DIR="/home/$USER/.cache/aur"

install () {
	cd "$CACHE_DIR" || exit

	for package in "$@"
	do
		[ "$package" = "install" ] && continue
	
		git clone "https://aur.archlinux.org/$package"

		cd "$package" || exit
	
		makepkg -si
	done	
}

update () {
	cd "$CACHE_DIR" || exit
	for package in "$CACHE_DIR"/*
	do
		package=$(echo "$package" | awk -F "/" '{print $NF}')

		git clone "https://aur.archlinux.org/$package" "$package-tmp"
		if [ "$(awk -F "=" '/^pkgver/ {print $2}' "$package/PKGBUILD")" != \
		       	"$(awk -F "=" '/^pkgver/ {print $2}' "$package-tmp/PKGBUILD")" ]
		then
			rm -rf "$package"
			mv "$package-tmp" "$package"
			cd "$package" || exit
			makepkg -si
		else
			rm -rf "$package-tmp"
		fi
	done
}

case "$1" in 
	install) install "$@" ;;
	update) update ;;
	*) echo "$0: [install update]" && exit ;;
esac
