#!/bin/sh

# gap a simple script to automate pushing to github

[ "$#" -lt 3 ] && echo "usage: $0 [branch] [comment] [file(s)]" && exit 1

shift 2

for i in "$@"; do
	git add "$i"
done

git commit -m "$2"

git push -u origin "$1"
