#!/bin/sh

# gap a simple script to automate pushing to github

[ "$#" -lt 3 ] && echo "usage: $0 [branch] [comment] [file(s)]" && exit 1

BRANCH="$1"
COMMENT="$2"

shift 2

for i in "$@"; do
	git add "$i"
done

git commit -m "$BRANCH"

git push -u origin "$COMMENT"
